from .bai import BAI as BAI
from .bca import BCA as BCA
from .bci import BCI as BCI
from .bfa import BFA as BFA
from .bir import BIR as BIR
from .bni import BNI as BNI
from .bpc import BPC as BPC
from .caixa import CaixaAngola as CaixaAngola
from .keve import Keve as Keve
from .sol import SOL as SOL
from .standard import StandardBank as StandardBank
